<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CozyTest</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Images\tests_img\**" />
    <Compile Remove="Models0\**" />
    <EmbeddedResource Remove="Images\tests_img\**" />
    <EmbeddedResource Remove="Models0\**" />
    <None Remove="Images\tests_img\**" />
    <None Remove="Models0\**" />
    <Page Remove="Images\tests_img\**" />
    <Page Remove="Models0\**" />
  </ItemGroup>


  <ItemGroup>
    <None Remove="connection.settings" />
    <None Remove="Images\add_picture_icon.png" />
    <None Remove="Images\add_picture_icon_2.png" />
    <None Remove="Images\back_logo.png" />
    <None Remove="Images\clear_icon.png" />
    <None Remove="Images\comments_icon.png" />
    <None Remove="Images\curator_icon.png" />
    <None Remove="Images\delete_icon.png" />
    <None Remove="Images\exam_icon.png" />
    <None Remove="Images\excel_icon.png" />
    <None Remove="Images\exit_logo.png" />
    <None Remove="Images\favorite.png" />
    <None Remove="Images\finish_icon.png" />
    <None Remove="Images\first_arrow_icon.png" />
    <None Remove="Images\follow_icon.png" />
    <None Remove="Images\group_icon.png" />
    <None Remove="Images\home_icon.png" />
    <None Remove="Images\icon.ico" />
    <None Remove="Images\magnifier_icon.png" />
    <None Remove="Images\menu_icon.png" />
    <None Remove="Images\participant_icon.png" />
    <None Remove="Images\plus_icon.png" />
    <None Remove="Images\profile_icon.png" />
    <None Remove="Images\relax_icon.png" />
    <None Remove="Images\requests_icon.png" />
    <None Remove="Images\result_icon.png" />
    <None Remove="Images\search_icon.png" />
    <None Remove="Images\settings_icon.png" />
    <None Remove="Images\sort_icon.png" />
    <None Remove="Images\statistic_icon.png" />
    <None Remove="Images\test_icon.png" />
    <None Remove="Images\time_icon.png" />
    <None Remove="Images\users_icon.png" />
    <None Remove="primerTest.xlsx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.5.1" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="5.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
    <PackageReference Include="Notifications.Wpf" Version="0.1.1" />
    <PackageReference Include="ScottPlot.WPF" Version="5.1.57" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="connection.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>connection.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\add_picture_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\add_picture_icon_2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\back_logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\clear_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\comments_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\curator_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\delete_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\exam_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\excel_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\exit_logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\favorite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\finish_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\first_arrow_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\follow_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\group_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\home_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\magnifier_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\menu_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\participant_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\plus_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\profile_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\relax_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\requests_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\result_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\search_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\second_arrow_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\settings_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\sort_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\statistic_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\test_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\time_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\users_icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="primerTest.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="connection.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>connection.settings</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
